snippets:
  - name: "Read Latest Result"
    description:
      pre: |
        Read an aggregator result on-chain

      post: |
        **Example(s)**:
        [anchor-feed-parser](https://github.com/switchboard-xyz/sbv2-solana/blob/main/programs/anchor-feed-parser/src/lib.rs),
        [native-feed-parser](https://github.com/switchboard-xyz/sbv2-solana/blob/main/programs/native-feed-parser/src/lib.rs)

    filename: "read-result.rs"
