image: "docker.io/switchboardlabs/node:$SBV2_NODE_IMAGE"
cluster: $CLUSTER
rpcUrl: $RPC_URL
wsUrl: $WS_URL
backupMainnetUrl: $BACKUP_MAINNET_RPC
googlePayerSecretPath: $GOOGLE_PAYER_SECRET_PATH
googleOracleSecretPath: $GOOGLE_PAYER_SECRET_PATH
keyJson: $SERVICE_ACCOUNT_BASE64
gcpConfigBucket: $GCP_CONFIG_BUCKET
metricsExporter: $METRICS_EXPORTER
pagerdutyEventKey: "$PAGERDUTY_EVENT_KEY"
heartbeatInterval: "$HEARTBEAT_INTERVAL"
nonceFlag: "$NONCE_FLAG"
nonceQueueSize: "$NONCE_QUEUE_SIZE"
unwrapStakeThreshold: "$UNWRAP_STAKE_THRESHOLD"
oracleKeys:
  - name: idx-1
    data: $ORACLE_KEY
  # - name: idx-2
  #   data: $ORACLE_KEY
