[package]
name = "basic-oracle-function"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "basic-oracle-function"
path = "src/main.rs"

[dependencies]
tokio = "^1"
futures = "0.3"
switchboard-solana = "0.5.2"
switchboard-utils = "0.5.0"
basic_oracle = { path = "../", features = ["no-entrypoint"] }
serde = "^1"
serde_json = "^1"
