[workspace]
members = [
    "."
]

[programs.localnet]
anchor_feed_parser = "Fstf3oTcBxHMZFaoBzxk5oSkTh5HaAjxjh6zcgdZpNBb"
[programs.devnet]
anchor_feed_parser = "Fstf3oTcBxHMZFaoBzxk5oSkTh5HaAjxjh6zcgdZpNBb"

[provider]
# cluster = "devnet"
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 ./tests/*.test.ts --exit"

[test.validator]
url = "https://api.devnet.solana.com"

[test]
startup_wait = 15000

[[test.validator.clone]] # sbv2 devnet programID
address = "2TfB33aLaneQb5TNVwyDz3jSZXS6jdW2ARw1Dgf84XCG"

[[test.validator.clone]] # sbv2 devnet IDL
address = "CKwZcshn4XDvhaWVH9EXnk3iu19t6t5xP2Sy2pD6TRDp"

[[test.validator.clone]] # sbv2 devnet SbState
address = "BYM81n8HvTJuqZU1PmTVcwZ9G8uoji7FKM6EaPkwphPt"

[[test.validator.clone]] # sbv2 devnet tokenVault
address = "FVLfR6C2ckZhbSwBzZY4CX7YBcddUSge5BNeGQv5eKhy"

[[test.validator.clone]] # sbv2 SOL/USD Feed
address="GvDMxPzN1sCj7L26YDK2HnMRXEQmQ2aemov8YBtPS7vR"