[workspace]
members = [
    "."
]

[programs.localnet]
anchor_feed_parser = "Fstf3oTcBxHMZFaoBzxk5oSkTh5HaAjxjh6zcgdZpNBb"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 ./tests/*.test.ts"

# [test.validator]
# url="https://api.devnet.solana.com"

# [test]
# startup_wait = 10000

# [[test.validator.clone]]
# address="GvDMxPzN1sCj7L26YDK2HnMRXEQmQ2aemov8YBtPS7vR" # sbv2 SOL/USD Feed