[workspace]
members = [
    "."
]

[provider]
# cluster = "devnet"
cluster = "localnet"
wallet = "../../../payer-keypair.json"
# wallet = "~/.config/solana/id.json"

[programs.localnet]
anchor_buffer_parser = "96punQGZDShZGkzsBa3SsfTxfUnwu4XGpzXbhF7NTgcP"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 ./tests/*.test.ts"


[test.validator]
url="https://api.devnet.solana.com"

[test]
startup_wait = 10000

[[testnet.validator.clone]]
address="GvDMxPzN1sCj7L26YDK2HnMRXEQmQ2aemov8YBtPS7vR" # sbv2 SOL/USD Feed

# [[test.validator.clone]] # programID
# address = "2TfB33aLaneQb5TNVwyDz3jSZXS6jdW2ARw1Dgf84XCG"

# [[test.validator.clone]] # idlAddress
# address = "CKwZcshn4XDvhaWVH9EXnk3iu19t6t5xP2Sy2pD6TRDp"

# [[test.validator.clone]] # programState
# address = "BYM81n8HvTJuqZU1PmTVcwZ9G8uoji7FKM6EaPkwphPt"

# [[test.validator.clone]] # switchboardVault
# address = "FVLfR6C2ckZhbSwBzZY4CX7YBcddUSge5BNeGQv5eKhy"

# [[test.validator.clone]] # tokenWallet
# address = "98noixB6NnabjgFKw9wgXtqVd9Xg6rmj5kEVMeCHUB5e"

# [[test.validator.clone]] # queue
# address = "AGhkGTuVfSGKYoFcRCUbbPNxhnaWNRXzcAYndyHdNV3V"

# [[test.validator.clone]] # queueAuthority
# address = "AXrbiv8bmcJfscyYWjR8BMFvTUjmx7FSENCjtEx4NxFh"

# [[test.validator.clone]] # queueBuffer
# address = "9SYE1tzHxKvRCYAv1yLLA4iMjk3p3VWiqgZX8v4HNBrw"

# [[test.validator.clone]] # crank
# address = "7xN6FXxJBtPVgrzcAZogvw7kWjz1NQdXmx7hoTVG3abF"

# [[test.validator.clone]] # crankBuffer
# address = "6pANimo6hHXShDcWdNZjsW6cbc2azGhcLGdnCBC4TBi8"

# [[test.validator.clone]] # oracle
# address = "JArZ6Van92SM6VyaARFmstgX2n9TJmLvVBN9ZkwpKH8B"

# [[test.validator.clone]] # oracleAuthority
# address = "AXrbiv8bmcJfscyYWjR8BMFvTUjmx7FSENCjtEx4NxFh"

# [[test.validator.clone]] # oracleEscrow
# address = "3Dm7ZuqNH89QLBuuJbqa4XZfpz8n1pCobP23NtVisQHE"

# [[test.validator.clone]] # oraclePermissions
# address = "GgNZcKzHBtEiLuDeaRAT8SsMTyG5Yzpm4XvetiazkHHW"
