[package]
name = "switchboard-solana"
version = "0.3.11"
edition = "2021"
description = "A Rust library to interact with Switchboard accounts."
readme = "README.md"
keywords = ["switchboard", "oracle", "solana"]
homepage = "https://docs.switchboard.xyz"
repository = "https://github.com/switchboard-xyz/sgx-sdk/tree/main/rust/solana"
license = "MIT"
documentation = "https://docs.switchboard.xyz"

[lib]
crate-type = ["cdylib", "lib"]
name = "switchboard_solana"
doctest = false

[features]
default = ["cpi"]
no-entrypoint = []
cpi = ["no-entrypoint"]

[dependencies]
anchor-spl = "=0.26.0"
solana-program = ">= 1.13.5, < 1.15"
rust_decimal = "^1"
bytemuck = "^1"
superslice = "1"
# These may not be needed, anchor27 keeps complaining
winnow = "=0.4.1"
toml_edit = "=0.19.8"
toml_datetime = "=0.6.1"

[target.'cfg(target_os = "solana")'.dependencies]
switchboard-common = { version = "0.1.6" }
anchor-lang = { version = "=0.26.0" }

[target.'cfg(not(target_os = "solana"))'.dependencies]
switchboard-common = { version = "0.1.6", features = ["sgx"] }
anchor-client = { version = "=0.26.0" }
bincode = { version = "^1" }
sgx-quote = { version = "0.1.0" }
cron = { version = "0.12.0" }
chrono = { version = "0.4.25" }

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"
targets = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "doc_cfg"]
