[package]
name = "switchboard-solana"
version = "0.3.7"
edition = "2021"
description = "A Rust library to interact with Switchboard accounts."
readme = "README.md"
keywords = ["switchboard", "oracle", "solana"]
homepage = "https://docs.switchboard.xyz"
repository = "https://github.com/switchboard-xyz/sgx-sdk/tree/main/rust/solana"
license = "MIT"
documentation = "https://docs.switchboard.xyz"

[lib]
crate-type = ["cdylib", "lib"]
name = "switchboard_solana"
doctest = false

[features]
default = ["cpi"]
no-entrypoint = []
cpi = ["no-entrypoint"]
client = [
    "switchboard-common/sgx",
    "solana-client",
    "bincode",
    "sgx-quote",
    "cron",
    "chrono"
]

[dependencies]
switchboard-common = { version = "0.1.3" }
rust_decimal = "^1"
bytemuck = "^1"
superslice = "1"
anchor-lang = "0.28.0"
anchor-spl = "0.28.0"
solana-program = ">= 1.14, < 1.17"
solana-sdk = ">= 1.14, < 1.17"
solana-client = { version = ">= 1.14, < 1.17", optional = true }
# anchor-client = { version = "0.28.0", optional = true }
bincode = { version = "^1", optional = true }
sgx-quote = { version = "0.1.0", optional = true }
cron = { version = "0.12.0", optional = true }
chrono = { version = "0.4.25", optional = true }
toml_datetime = "=0.6.1"
winnow = "=0.4.1"
toml_edit = "=0.19.8"
