[package]
name = "switchboard-solana"
version = "0.3.10"
edition = "2021"
description = "A Rust library to interact with Switchboard accounts."
readme = "README.md"
keywords = ["switchboard", "oracle", "solana"]
homepage = "https://docs.switchboard.xyz"
repository = "https://github.com/switchboard-xyz/sgx-sdk/tree/main/rust/solana"
license = "MIT"
documentation = "https://docs.switchboard.xyz"

[lib]
crate-type = ["cdylib", "lib"]
name = "switchboard_solana"
doctest = false

[features]
default = ["cpi", "anchor-lang"]
no-entrypoint = []
cpi = ["no-entrypoint"]
client = [
    "switchboard-common/sgx",
    "anchor-client",
    "bincode",
    "sgx-quote",
    "cron",
    "chrono"
]

[dependencies]
switchboard-common = { version = "0.1.6" }
rust_decimal = "^1"
bytemuck = "^1"
superslice = "1"
# Anchor Deps
anchor-lang = { version = "0.26.0", optional = true }
anchor-spl = "0.26.0"
anchor-client = { version = "0.26.0", optional = true }
# anchor-lang = "0.26.0"
# anchor-spl = "0.26.0"
# Solana Deps
solana-program = ">= 1.13.5, < 1.15"
# solana-sdk = { version = ">= 1.13.5, < 1.15", optional = true }
# solana-client = { version = ">= 1.13.5, < 1.15", optional = true }
# anchor-client = { version = "0.28.0", optional = true }
bincode = { version = "^1", optional = true }
sgx-quote = { version = "0.1.0", optional = true }
cron = { version = "0.12.0", optional = true }
chrono = { version = "0.4.25", optional = true }
