name: solana-js-test
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "javascript/solana.js/src/**"
      - "javascript/solana.js/test/**"
      - "javascript/solana.js/package.json"
      - "javascript/solana.js/package-lock.json"

env:
  ANCHOR_VERSION: 0.25.0
  CARGO_TERM_COLOR: always
  SOLANA_VERSION: 1.13.5

jobs:
  solana_js_devnet_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: Build solana.js
        working-directory: javascript/solana.js
        run: npm install && npm run build
      - name: Start Local Validator
        uses: switchboard-xyz/solana-local-validator@v0.1
        with:
          solana-version: v1.14.10
          anchor-version: v0.25.2
          cluster: devnet
          args:
            "--url https://api.devnet.solana.com  --clone
            2TfB33aLaneQb5TNVwyDz3jSZXS6jdW2ARw1Dgf84XCG --clone
            J4CArpsbrZqu1axqQ4AnrqREs3jwoyA1M5LMiQQmAzB9 --clone
            CKwZcshn4XDvhaWVH9EXnk3iu19t6t5xP2Sy2pD6TRDp --clone
            BYM81n8HvTJuqZU1PmTVcwZ9G8uoji7FKM6EaPkwphPt --clone
            FVLfR6C2ckZhbSwBzZY4CX7YBcddUSge5BNeGQv5eKhy"
      - name: Run Tests
        working-directory: javascript/solana.js
        run: npm run test:localnet
